### ISSUE TITLE
No plots for option "plot variances" and more than one policy rule

### ISSUE THREAD

**Issue by JTWendelborn** [IMFS-MMB/mmb-gui-electron#51]
When I select the option "Plot Variances" and more than one policy rule, the simulations are done, but no plots are shown. Is this expected behavior?

This occurs e.g. for NK_AFL15, rules CEE and CMR, MP shock, standard mmb variables and option Plot variances, but also for all other models I tried. 

Again, macOS 10.13, both Matlab and Octave.

**Comment by gboehl** [comment]
Maybe labeling it "show variances" or "print variances" would be beneficial.
@millazar @btatar13 ?

**Comment by millazar** [comment]
Indeed. In the previous MMB version within the output options, we had- unconditional variances. Both "show variances" and "print variances" sound good to me for the new version. If I had to choose one, I would go with the former.

Cheers,
L

________________________________

**Comment by gboehl** [comment]
@JTWendelborn was that your issue, that you were expecting plots instead of a table?
@millazar Thanks for the input. I'll relabel it.

**Comment by JTWendelborn** [comment]
@gboehl  Sorry, that I was not more specific. What I meant was that when I select more than one policy rule and select the option "plot/show variances", no output is shown at all, neither the table with the variances, nor the plots with the IRFs (although the simulations are done). When only one policy rule is selected, it works fine and shows IRFs and the table with the variances.

**Comment by j2L4e** [comment]
fixed via af2f94f

**Comment by AlexDece** [comment]
I still have this issue with no output at all (no table, no IRFs) when checking "plot variances" in the options. I installed the latest version of the MMB available under the link Gregor sent us for testing. 
http://build.macromodelbase.com/
Still the same issue.

It is independent of choosing 1 or more policy rules, shocks, variables, models. 
It is independent of also checking "plot acf"

Problem occured under Windows10, Octave 4.4.1, Dynare 4.5.7.
@JTWendelborn Please check (possibly tomorrow before lunch) if it still occurs for MAC
