### ISSUE TITLE
Failed to launch the MMB interface

### ISSUE THREAD

**Issue by cch388** [IMFS-MMB/mmb-gui-electron#70]
Hi Jan and Gregor, 

The MMB interface is failed to launch on my MacBook, with four blue circles shining as you can see in the attached screenshots. The problem remains even after I re-forked and re-cloned everything under the master branch.
<img width="1280" alt="Screen Shot 2019-11-22 at 2 59 12 PM" src="https://user-images.githubusercontent.com/46269849/69432399-ef75e780-0d39-11ea-8c7c-dfbd68d0653b.png">

I also attached the terminal report and the console report below for your reference.
<img width="551" alt="Screen Shot 2019-11-22 at 3 10 50 PM" src="https://user-images.githubusercontent.com/46269849/69432647-63b08b00-0d3a-11ea-9967-36ae4715d5ab.png">
[Report.txt](https://github.com/IMFS-MMB/mmb-gui-electron/files/3879848/Report.txt)

Thanks for the help!

Best,
Jin

**Comment by j2L4e** [comment]
Are the circles still animating? Can you click stuff or is the UI frozen?

Did you delete `node_modules` and run `npm install`?

**Comment by cch388** [comment]
Yes, the circles animate and no models are shown so I cannot click anything. 

Yes, I deleted everything in my repository, re-forked and re-cloned from the master branch, and run `npm install`. :(

**Comment by j2L4e** [comment]
What's the MMB path, shown in the settings modal?

There were several other minor issues. I've pushed a new version, does that work?

**Comment by cch388** [comment]
Hi Jan, 

Now the models are shown but I cannot scan or find Dynare manually and therefore still cannot simulate any models. Please see the screenshot. Thanks!
<img width="1280" alt="Screen Shot 2019-11-25 at 11 18 45 AM" src="https://user-images.githubusercontent.com/46269849/69532158-87abe080-0f75-11ea-8a35-1da87241fdd4.png">

**Comment by j2L4e** [comment]
> cannot scan or find Dynare manually
please elaborate

**Comment by cch388** [comment]
When I pressed the button "Scan" and "Find manually", nothing happened, as you can see there's a path for MatLab but nothing for Dynare.

**Comment by j2L4e** [comment]
When you "Find manually", does the file dialog open? Does it open when you try press "Find manually" in the matlab/octave section?

**Comment by cch388** [comment]
1. Yes. But after I clicked "Open," nothing is shown. Please see attached screenshot.
<img width="1280" alt="Screen Shot 2019-11-25 at 11 51 11 AM" src="https://user-images.githubusercontent.com/46269849/69534384-fab75600-0f79-11ea-8134-23f6e2597de4.png">

2. Yes. Everything works fine with Matlab. Please see attached screenshot.
<img width="1280" alt="Screen Shot 2019-11-25 at 11 50 06 AM" src="https://user-images.githubusercontent.com/46269849/69534428-128eda00-0f7a-11ea-88f6-0c75ce6ae744.png">

**Comment by j2L4e** [comment]
In that case your prior statement is not actually true
> When I pressed the button [...] "Find manually", nothing happened

Please be as precise as possible about the problem, so I can help you better :+1: 
I merged a fix into master
